### ISSUE TITLE
todonotes with AGUTeX.cls

### ISSUE THREAD

**Issue by bandre** [henrikmidtiby/todonotes#1]
Has anyone successfully used todonotes with the AGU style file (ftp://ftp.agu.org/journals/latex/journals/Manuscript-Preparation/agutex.cls). The notes start at the mid-point of the margin and must be extremely narrow to remain on the page. I tried the setlength marginparwidth trick, but it didn't seem to help. The listoftodos also doesn't work. 

My distribution is using the 2009/08/01 version of todonotes, but the 2010/09/13 version appears to have the same problem (the 2009/12/07 fix did not help?).

A simple example:

    \documentclass[draft,jgrga]{AGUTeX}
    \usepackage{todonotes}
    \begin{document}
    \begin{article}
    \section{Introduction}
    This is some text. Some more text. This is some text. Some more text.
    This is some text. Some more text. This is some text. Some more text.
    Article text \todo{this is a broken todo} here. This is some text.
    Some more text. This is some text. Some more text. This is some text.
    Some more text. \todo[inline]{need to finish this section} 
    \listoftodos
    \end{article}
    \end{document}

**Comment by henrikmidtiby** [comment]
I will close this issue. Please reopen if you get new information on the case.
