### ISSUE TITLE
preview and todonotes do not work together.

### ISSUE THREAD

**Issue by mforbes** [henrikmidtiby/todonotes#13]
M(n)WE:

```latex
\documentclass{article}
\usepackage{todonotes}
\usepackage{preview}
\begin{document}
Oops.
\end{document}
```

compilation yields:

```
...
! Undefined control sequence.
\@EveryShipout@Output ...EveryShipout@Org@Shipout 
                                                  \box \@cclv 
l.6 \end{document}
```

**Comment by henrikmidtiby** [comment]
Thanks for the error report.

I can reproduce the issue and have located it to be related to the tikz package

    \documentclass{article}
    \usepackage{tikz}
    \usepackage{preview}
    \begin{document}
    Oops.
    \end{document}

A workaround is to add active option when loading the preview package

    \documentclass{article}
    \usepackage{tikz}
    \usepackage[active]{preview}
    \begin{document}
    Oops.
    \end{document}

Based on the above I have closed the issue.
