### ISSUE TITLE
Missingfigure image is a 'give-way-sign' not a 'warning' sign

### ISSUE THREAD

**Issue by hildensia** [henrikmidtiby/todonotes#14]
The image of `\missingfigure{}` is a give-way-sign/yield-sign, which in my view doesn't make sense. You probably wanted to make a warning sign, but that is upside-down.

(This is arguably a very minor issue :-) I wanted to note it anyway)

**Comment by henrikmidtiby** [comment]
Thanks for the bug report, although I will close it without further actions, as I also consider it a minor issue.
