### ISSUE TITLE
hlfix example does not obey disabled todos

### ISSUE THREAD

**Issue by MaPePeR** [henrikmidtiby/todonotes#17]
The [`\hlfix`-Example](https://github.com/henrikmidtiby/todonotes/blob/0078e8ccedc51fa05012250fc9b8e7c736705537/todonotes.dtx#L1119-L1128) does not remove the highlight from the word, if todonotes is disabled. 

I suggest changing the example to

```latex
\makeatletter
\if@todonotes@disabled
\newcommand{\hlfix}[2]{#1}
\else
\newcommand{\hlfix}[2]{\texthl{#1}\todo{#2}}
\fi
\makeatother
```

**Comment by henrikmidtiby** [comment]
Thanks for the suggestion. It will be included in the next release.
