### ISSUE TITLE
Package option english missing in Doc

### ISSUE THREAD

**Issue by fabianrost84** [henrikmidtiby/todonotes#18]
`english` also seems to be a package option but it is missing in the documentation pdf. 

I stumbled across it like this (to illustrate that the option is needed):
For some reason `todonotes` automatically selected German as the language in my latex document. That was not surprising as the document is partly in English and partly in German (defined like this `\documentclass[ngerman,american,BCOR=6mm,cdgeometry=no,DIV=13,declaration=heading]{tudscrreprt}`). However, I wanted the todonotes in English.

So also the sentence "The default is to use none of these options, which results in english text strings." in the documentation seems to be wrong.

**Comment by henrikmidtiby** [comment]
Thanks for notifying me about the error in the documentation. It will be fixed in the next release.
