### ISSUE TITLE
Compilation speed. Miktex vs texlive 

### ISSUE THREAD

**Issue by MaPePeR** [henrikmidtiby/todonotes#19]
I work on the same document on 2 very different devices. One windows, one Linux, one miktex, one texlive. (using texstudio on both) 

On the Linux computer with texlive I never had any problems with compilation speed. On the windows miktex computer I noticed a major slowdown of compilation speed, when todonotes is not disabled. 
Mostly caused by a lot more compilations runs compared to texlive. (6 runs every time in contrast to 1 on texlive)

This might be part of the reason, why this package is [listed for causing major slowdown](http://tex.stackexchange.com/a/8793). 

This probably needs more investigation. I did not do a real test to see if it is really caused by the miktex + todonotes combination.

**Comment by buhtz** [comment]
Have you tested the speed between this two machines with other packages or simple tex-code, too?

I have very high speed differences between Windows and Linux (with TeXLive). But they are independend from any package.

**Comment by MaPePeR** [comment]
The slowdown disappeared when I disabled todonotes on the windows machine.

**Comment by henrikmidtiby** [comment]
The possibility of todonotes slowing down the compilation is mentioned in the documentation. I don't have any ideas of dealing with this issue, as it is tightly coupled to the core parts of the package.
