### ISSUE TITLE
Marginnote instead of marginpar

### ISSUE THREAD

**Issue by aleth** [henrikmidtiby/todonotes#2]
Not so much an issue as a suggestion: I have modified todonotes to use the marginnote package, which replaces the \marginpar command with something which works much better. Apart from requiring the package, minimally only one line has to be changed (use \marginnote rather than \marginpar).

Advantages:

- all those pesky marginpar warnings are gone

- I no longer have the problems with line spacing for smaller font sizes I had before. (Even with the setspace package method, a lot of extra space is wasted, at least for me.) Everything "just works" as long as the font size is set for the marginnotes in the main document, e.g. <pre>\renewcommand*{\marginfont}{\tiny}</pre>(This must be done *after* loading the todonotes package.) The todonotes textsize option is still useful, e.g. for setting the font family (I use textsize=sffamily).

Thanks for the nice package!

**Comment by henrikmidtiby** [comment]
It is quite easy to switch all occurences of marginpar with marginnote.
It is explained in section "1.6.8 Todonotes in footnotes" in the documentation.

I will not make it default to use in the package, as marginpar has the feature that inserted notes does not overlap. This is not the case when using marginnote.
