### ISSUE TITLE
Change the font

### ISSUE THREAD

**Issue by karbecker** [henrikmidtiby/todonotes#20]
Hi!

There is no option to change the font family to sans serif family, is there?

Thanks

Karl

**Comment by buhtz** [comment]
I would say this is not in the responsibility of that package. You can do this by yourself.

quick and dirty example

```
\newcommand{\osenf}[1] {%
    \todo[
        size=\scriptsize
        ]
        { %
                \sffamily #1
        } %
}
```

**Comment by henrikmidtiby** [comment]
As noMICROSOFTbuhtz mentions it is not a responsibility of the todonotes package.
Therefore it is much better handled by the user.
