### ISSUE TITLE
Overlap of Todo if author is defined

### ISSUE THREAD

**Issue by khalid-hussain** [henrikmidtiby/todonotes#22]
Taken from [TeX.SE](http://tex.stackexchange.com/), [Double (overlapped) TODO note in margin](http://tex.stackexchange.com/questions/341921/double-overlapped-todo-note-in-margin).

MWE (taken from the question),

```latex
\documentclass[]{article}
\usepackage{todonotes}
\begin{document}
This is \todo[size=\tiny,author=Me]{Here's a long comment that wraps around in the margin}a
test
\end{document}
```

![wixek](https://cloud.githubusercontent.com/assets/3102714/20819981/e55e5558-b872-11e6-92f6-fea6aea28797.png)

**Comment by fuhrmanator** [comment]
I reported this in TeX.SE. I'm not a TeX programmer and don't know how to go about testing a fix, but I think the problem lies within the block at line 1728:

```tex
    \begin{tikzpicture}[remember picture,baseline=(X.base)]%
        \node(X){\vphantom{X}};%
        \draw node[notestyle,font=\@todonotes@sizecommand,anchor=north] (inNote) at (X.north)%
            {\@todonotes@text};%
        \if@todonotes@authorgiven%
            \draw node[notestyle,font=\@todonotes@sizecommand,anchor=north] (inNote) at (X.north)%
                {\@todonotes@sizecommand\@todonotes@author};%
            \node(Y)[below=of X]{};%
            \draw node[notestyle,font=\@todonotes@sizecommand,anchor=north] (inNote) at (X.south)%
                {\@todonotes@text};%
        \else%
            \draw node[notestyle,font=\@todonotes@sizecommand,anchor=north] (inNote) at (X.north)%
                {\@todonotes@text};%
        \fi%
    \end{tikzpicture}%
```

The `\draw node...` lines just before the `\if@todonotes@authorgiven%` and after the `\else%` seem to be where the duplication is happening. 

Hope this is useful.

**Comment by henrikmidtiby** [comment]
Fixed in 
https://github.com/henrikmidtiby/todonotes/commit/406c00bc74848fb8c2d1ed3c0721169bb18c2d16
