### ISSUE TITLE
Todonotes styles

### ISSUE THREAD

**Issue by jspitz** [henrikmidtiby/todonotes#23]
I think it would be a helpful feature if one could define todonotes "styles" that define different settings globally. This would enhance the usage for multiple authors or categories. Something like
```
\settodostyle{peter}{author=Peter,color=green}
\settodostyle{paul}{author=Paul,color=blue,disable}
```

And then

`\todo[style=peter]{Peter's comment} \todo[style=paul]{Paul's comment}`

**Comment by henrikmidtiby** [comment]
You can already do something similar, by defining new commands like shown here


```
\documentclass{article}
\usepackage{todonotes}

\newcommand{\todopeter}[2][]{\todo[color=green, #1]{Peter: #2}}
\newcommand{\todopaul}[2][]{\todo[color=blue, disable, #1]{Paul: #2}}

\begin{document}
Some text
\todopeter{test}
more text
\todopaul{tester}
\end{document}
```

**Comment by jspitz** [comment]
I know that I can define my own commands, but I don't think this obsoletes the feature request. Your call, of course.
