### ISSUE TITLE
Place todos on the inner margin.

### ISSUE THREAD

**Issue by leiterschleife** [henrikmidtiby/todonotes#27]
Is it possible to place a `\todo` on the inner margin of the page? I could not find an option in the docs that allows to specify on which margin to place the comment. Sometimes, in case of many comments on one page, the comments tend to bloat the margin and it is not possible to find the corresponding text anymore. So making use of the other margin available would be useful.

**Comment by henrikmidtiby** [comment]
You can manually do something like shown below to alter the side in which todonotes / marginpars are shown.

```
\documentclass{article}
\usepackage{todonotes}
\begin{document}
Shifting marginpars up and down.
\todo{test 1} 
\todo{test 1} 

\reversemarginpar

Shifting marginpars up and down.
\todo{test 1} 
\todo{test 1} 
\end{document} 
```
