### ISSUE TITLE
TODO Notes cannot be placed in `\footnote`s: "Float(s) lost"

### ISSUE THREAD

**Issue by ErikBoesen** [henrikmidtiby/todonotes#28]
Simple example can be found in [this gist](https://gist.github.com/ErikBoesen/e8e93b4e59a6e7a24525a1faca77fe65).

I tested this on my MacBook Air with OS X El Capitan and on Arch Linux, using `pdflatex`.

**Comment by henrikmidtiby** [comment]
Thanks for the example.
It is a known issue that floats are losts in figure captions and footnotes.
My solution were to add inline todonotes to the package.
The inline todonotes are used as follows.

```
\documentclass{article}
\usepackage{todonotes}

\begin{document}
This is an example of TODO notes breaking build when used in footnotes.\footnote{Here's a footnote.\todo[inline]{This doesn't work.}}
\end{document}
```

**Comment by ErikBoesen** [comment]
Awesome! I appreciate your attention!
