### ISSUE TITLE
Notes are crushed in two-column layout

### ISSUE THREAD

**Issue by ErikBoesen** [henrikmidtiby/todonotes#29]
I'm using 
```tex
\documentclass[twocolumn]{article}
```
When I try to use a `\todo{}`, the note box is pressed to the body text like so:
![](https://user-images.githubusercontent.com/5923662/40888622-c7f753c4-6727-11e8-9839-1fbe9d8c2e95.png)
I fixed this for my own document by using
```tex
\setlength{\marginparwidth}{2cm}
```
That solution isn't perfect, but it's about as good as you can get with the admittedly limited space.
![](https://user-images.githubusercontent.com/5923662/40888650-125516f4-6728-11e8-9ea9-274971295f79.png)

**Comment by henrikmidtiby** [comment]
Your solution is the same as I would recommend. I think that the actual error is in the article documentclass which fails to set the proper value of marginparwidth.

**Comment by ErikBoesen** [comment]
Is there a way to warn users through this package that such a problem might occur? Admittedly I'm not a (La)TeX expert, so I don't know.

**Comment by henrikmidtiby** [comment]
Thats an interesting idea. It should be possible to look at the magnitude of marginparwidth and if it is below a certain threshold, like 2 cm, an error should be given. I will look at this option.

**Comment by henrikmidtiby** [comment]
Added to the new release.

**Comment by clason** [comment]
I find this new behavior very intrusive -- is it possible to turn it into a console warning or at least an option (default to off for compatibility)?

**Comment by AdrianVollmer** [comment]
I agree with @clason. Outputting warnings in the document is unacceptable.

**Comment by ErikBoesen** [comment]
Is that what's happening? I agree.

**Comment by henrikmidtiby** [comment]
Thanks for the comments. I will change the notice to a warning.



fre. 13. jul. 2018 14.39 skrev Erik Boesen <notifications@github.com>:
