### ISSUE TITLE
PDF annotations

### ISSUE THREAD

**Issue by vidartf** [henrikmidtiby/todonotes#3]
When compiling to PDF with pdflatex it would be good to have the option to have the todos implemented as comments. I can't see this working for inline or missing figures, but at least for the margin notes this could be useful. The pdfcomment package might be of use:

"Though pdflatex provides the command \pdfannot for pdf annotations it is somehow complicated to use. The new package pdfcomment offers a user-friendly way to insert comments/ annotations into pdf files."

Its licence is LPPL.

**Comment by buhtz** [comment]
Would be a very nice feature. I assume there is a lot of work behind it.

**Comment by henrikmidtiby** [comment]
I think that this is best left for the `pdfcomment` package.
