### ISSUE TITLE
todonotes warning fucks up formatting of document

### ISSUE THREAD

**Issue by baueli** [henrikmidtiby/todonotes#32]
I get the following warning as the first page of my document:

> Warning. The length \marginparwidth is less than 2cm and will most likely cause issues with the appearance of inserted todonotes. The issue can be solved by adding a line like \setlength{\marginparwidth}{2cm} prior to loading the todonotes package.

This fucks up the formatting of the template to the journal i'm submitting. With a three week old package of there is no issue. Just the current version. Why not display warnings in console?

**Comment by henrikmidtiby** [comment]
It is much better to display the warning in the console. This is the behaviour on 1.0.7 that was submitted to ctan a few minutes ago.
