### ISSUE TITLE
tikz.sty not found, updated miktex today

### ISSUE THREAD

**Issue by OliverFishCode** [henrikmidtiby/todonotes#34]
Updated Miktex today 1/7/2019 at 11:30am Arizona Time and the below error is being thrown.  Based on atom and latex log todonotes is the source.
This is the error:
! LaTeX Error: File `tikz.sty' not found.

This error no longer occurs after commenting out:
 \usepackage[textsize=tiny]{todonotes}

**Comment by FrankMittelbach** [comment]
the todonotes package uses a few other package some of them only in certain layouts (I think it is documented in the documentation for todonotes but can't check that right now). Obviously your installation is missing tikz (and you haven't configured miktex to load missing packages).

**Comment by OliverFishCode** [comment]
Thats the thing I do have it configured to install missing packages

**Comment by OliverFishCode** [comment]
I discovered that this was a MikTex packaging error that will be fixed soon. Turns out todonotes was just triggering the error as a result of missing file in packaging.
Link to issue located here: 
https://github.com/MiKTeX/miktex-packaging/issues/80
