### ISSUE TITLE
Incompatibility with longtabu?

### ISSUE THREAD

**Issue by drewx0r** [henrikmidtiby/todonotes#35]
Recently, a document stopped compiling, throwing an error when longtabu, which requires longtable and tabu, was used with the X option for one of the columns. Removing the todonotes package eliminated the error. 

```latex
\documentclass[12pt]{article}
\usepackage{geometry}   
\geometry{letterpaper}   

\usepackage{longtable}
\usepackage{tabu}
\usepackage{todonotes}

\begin{document}
\begin{longtabu}{l X}
hello & goodbye
\end{longtabu}
\end{document}
```

**Comment by FrankMittelbach** [comment]
It is tabu that is broken not todonotes, You get the same problem when you load color instead of todonotes. See https://github.com/latex3/latex2e/issues/111 for workarounds

**Comment by henrikmidtiby** [comment]
Closed the issue based on Franks comment.

**Comment by albert-github** [comment]
I think it is worth mentioning the new repository: https://github.com/tabu-fixed/tabu
