### ISSUE TITLE
Inlined todo notes can lead to corrupted bullets in itemize 

### ISSUE THREAD

**Issue by schaetzc** [henrikmidtiby/todonotes#37]
Using an inlined todo note inside an itemize environment sometimes swallows the bullet point in front of the note and inserts it as an overlay of the first bullet point in the next itemize environment.

Minimal example `main.tex`
```
\documentclass{article}
\usepackage[]{todonotes}
\presetkeys{todonotes}{inline}{}
\begin{document}
Unaffected list causing a problem
\begin{itemize}
	\item a
	\begin{itemize}
		\item b
	\end{itemize}
	\item \todo{note}
\end{itemize}
Affected list
\begin{itemize}
	\renewcommand\labelitemi{X}
	\item Item with bug
	\item Correct item
\end{itemize}
\end{document}
```    
Compiling with `pdflatex main.tex` or `latex main.tex` both yield the following result:

![bulletbug](https://user-images.githubusercontent.com/14296809/51543263-75e14480-1e5d-11e9-9625-73e9c843e7f8.png)
 
The nested itemize environment is necessary, the bug does not occur without it.

Used versions are `pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2018/Arch Linux)`, `todonotes 2018/11/22 v1.1.1`, and `article.cls 2014/09/29 v1.4h`.

**Comment by henrikmidtiby** [comment]
Thanks for the bug report.
Right now I have no idea of what is causing the problem.
As the severity of the bug is limited I will close the issue.

**Comment by FrankMittelbach** [comment]
Correction: this is better placed in the definition of \todo and then also solves #36 
```

\makeatletter
\renewcommand{\todo}[2][]{%
% Needed to output any dangling \item of a noskip section (see #36):
    \if@inlabel \leavevmode \fi     
    \if@noskipsec \leavevmode \fi
% -------  
  \if@todonotes@inlinepar
    \ifhmode
      \@bsphack
      \@todonotes@vmodefalse
    \else
      \@savsf\@m
      \@savsk\z@
      \@todonotes@vmodetrue
    \fi
    {\@todo[#1]{#2}}%
    \@esphack%
    \if@todonotes@vmode \par \fi
  \else%
    \@todo[#1]{#2}%
  \fi}

\makeatother
```

**Comment by henrikmidtiby** [comment]
Thanks for the patch. It will be included in the next release.

**Comment by schaetzc** [comment]
Thank you for the patch! With `\leavevmode` all bullets stay where they belong.

Note that the patch changes the placement of todo notes if the appear directly after `\item` no matter if that specific item was affected by the bug or not. I think that's the lesser of two evils. However, there might be a workaround, for instance something like `\vspace{-\baselineskip}` after `\leavevmode`.

![patchvsnopatch](https://user-images.githubusercontent.com/14296809/51689600-49613000-1ff7-11e9-8e29-bb78b7e9130b.png)

**Comment by FrankMittelbach** [comment]
That might be possible but not unconditionally. It should only happen if you are `@inlabel` and the `inlinepar` is also specified, in other cases it would be wrong (and it would need to come bfore not after the `\leavvmode`), eg something like
```
    \if@inlabel 
         \if@todonotes@inlinepar \vspace{-\baselineskip}\fi
         \leavevmode \fi          % item not yet placed
    \if@noskipsec \leavevmode \fi    % inline heading not yet placed
```
Not tested though.
