### ISSUE TITLE
Multiple \listoftodos vs. allow todo item not to be shown on \listoftodos

### ISSUE THREAD

**Issue by staerz** [henrikmidtiby/todonotes#44]
First of all, thanks for this great package! Very easy to use!

## Feature Request Summary

- Introduce an option for the todo item not to appear in the `\listoftodos`
- Alternatively a feature to have multiple `\listoftodos` for different kinds of todo items would be very helpful

## Feature Details

In a current project, I used `\todo` to define my own macros, e.g. this one:
```tex
\newcommand{\fixit}[2][]{\stepcounter{fixitcnt}\todo[inline,bordercolor=red,color=red!50,#1]{\textbf{FIX IT [\thefixitcnt]:} #2}}
```
together with the counter `\newcounter{fixitcnt}`, of course.

Now, for my case it is necessary to have a dedicated todo list for a certain kind of todo items and I didn't manage to configure `todonotes` to do so.

I successfully managed to create my own todolist for a certain category items:

```tex
\newcommand{\addElementToReviewList}{%
    \if@todonotes@colorinlistoftodos%
        \addcontentsline{lorev}{reviewcomments}{%
            \fcolorbox{\@todonotes@currentbordercolor}%
                {\@todonotes@currentbackgroundcolor}%
{\textcolor{\@todonotes@currentbackgroundcolor}{o}}%
            \ \@todonotes@caption}%
    \else%
\addcontentsline{lorev}{reviewcomments}{\@todonotes@caption}%
    \fi%
}%
```

Then defining

```tex
\newcounter{reviewcnt}
\newcommand{\review}[1]{\stepcounter{reviewcnt}\todo[inline,bordercolor=Apricot,color=Apricot!50]{\textbf{REVIEW [\thereviewcnt]:} #1}\addElementToReviewList}
```
does the trick.

So adding an item to another (self-defined) list is no problem, but I can't make this review item disappear from the `\listoftodos` (e.g. via a "dontlist" or "notlist" or so option).

## Purpose, Expected Benefit

- Separate different kinds of todos in distingt lists.
- Increase overview in long documents on open todos.

**Comment by henrikmidtiby** [comment]
Thanks for the feature request. 
Please take a look at the `nolist` option to the todo command. 
It is briefly mentioned in the documentation at the bottom on page 6.

**Comment by staerz** [comment]
Dear Henrik,

thanks for the quick reply. Indeed, your suggested solution does what I want!

I'm sorry to have overlooked this documented feature in the first place.
