### ISSUE TITLE
polyglossia and textsize incompatibility

### ISSUE THREAD

**Issue by camilstaps** [henrikmidtiby/todonotes#45]
There appears to be an incompatibility when using `polyglossia` for XeLaTeX with `todonotes` and the `textsize` option. Consider the following example:

```tex
\documentclass{article}

\usepackage[textsize=footnotesize]{todonotes}

\usepackage{polyglossia}
\setmainlanguage[variant=british]{english}
\setotherlanguage{hebrew}

\begin{document}

\todo{x}

\end{document}
```

This results in the text `footnotesizex` in the footnote (in normal size).

Loading `todonotes` after `polyglossia` makes it work:

```tex
\usepackage{tikz}

\usepackage{polyglossia}
\setmainlanguage[variant=british]{english}
\setotherlanguage{hebrew}

\usepackage[textsize=footnotesize]{todonotes}
```

I believe more packages require to be loaded in a specific order. If this is a necessary, perhaps a warning can be added? (Try to remove the `tikz` line from the last example: `color` then warns that it is loaded after `bidi`.)

**Comment by henrikmidtiby** [comment]
Thanks for reporting this issue. I have added a comment about the package loading order when using both todonotes and polyglossia
