### ISSUE TITLE
todonote in environments is misplaced, has interactions with other todonotes

### ISSUE THREAD

**Issue by christophra** [henrikmidtiby/todonotes#49]
**0.** I have one experience putting a todo{} inside an equation:
`\begin{equation}\todo{0a}\end{equation}`
The todonote 0a ends up two pages down, pointing to approximately the spot on that page where the equation is on the correct page. If I instead make it inline, i.e. 
`\begin{equation}\todo[inline]{0b}\end{equation}`
then a todonote appears under the equation: but rather than the text 0b, it has the text of the document's preceding todonote. (It still appears in the the todolist, however.)

I've also had two experiences with putting a \todo{} inside a caption:
**1.** Under a table: the todonote is on the page, it's arrow (fancyline) points into the lower corner, the table is nowhere in the document.
**2.** Under a figure, this is interesting: I have the document set up as follows
`
\begin{figure}\caption{\todo{1}}\end{figure}
Body text \todo{2}. Further body text.
` 
Within the three pages containing the figure and body text, the todonotes end up as follows.
Page 1: Body text, and todonote 2, with the arrow (fancyline) pointing to a random spot on the page.
Page 2:  Contains the figure and its caption, but not todonote 2 anymore (obviously).
Page 3: Contains todonote 1, with the arrow (fancyline) pointing to a random spot on the page.

The latter two cases might be duplicates of https://github.com/henrikmidtiby/todonotes/issues/28 where it's already been indicated that it won't be fixed. In the first case, it's a whole different situation, though, the only similarity is that it's an environment and not just body text or a heading.

**Comment by henrikmidtiby** [comment]
Thanks for the bug report. 
I would appreciate a minimal working example where you demonstrate the problems. 
It makes it much easier for me to investigate the issue (and maybe suggest a solution) - [link1](https://www.texfaq.org/FAQ-minxampl) - [link2](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that).

For the first issue you mention, I think it will work if you put the todonote in a mbox or text command inside the math environment and also replace the marginpar command with the marginnote command.


```
\documentclass{article}
\usepackage{todonotes}
\usepackage{marginnote}
\let\marginpar\marginnote

\begin{document}
\begin{equation}
a^2=b^2+c^2  \textrm{\todo{Test}}
\end{equation}

\end{document}
```

**Comment by henrikmidtiby** [comment]
I try to avoid inserting todonotes inside a figure caption. Instead I place an inline todo right after the figure caption, as shown below:

```
\documentclass{article}
\usepackage{todonotes}
\begin{document}
\begin{figure}
\caption{A caption for the figure}
\todo[inline]{Find a proper figure}
\end{document}

```
