### ISSUE TITLE
Incompatibility with standalone package

### ISSUE THREAD

**Issue by moi90** [henrikmidtiby/todonotes#53]
When using `\todo{...}` in a standalone file, I get the following error: `You can't use `\end' in internal vertical mode.`

```latex
\documentclass[class=article,crop=false,a4paper]{standalone}
%\documentclass{article}
\usepackage{todonotes}

\begin{document}
    \todo{Test}Lorem ipsum
\end{document}
```

There is also an according StackOverflow question: https://tex.stackexchange.com/questions/304260/is-there-a-way-to-use-todonotes-in-standalone

I believe it should be possible without any hacks.

**Comment by henrikmidtiby** [comment]
The problem is related to the `\marginpar` command. The same error as you report is observed in the document
```
\documentclass[crop=false]{standalone}

\begin{document}
Lorem ipsum
\marginpar{Testing}
\end{document}
```

If you replace the `\marginpar` command with `\marginnote` command, the issue disappears. By using `\marginnote` the inserted todos might overlap, which `\marginpar` prevents. The code below show how to do this.

```
\documentclass[class=article,crop=false,a4paper]{standalone}
\usepackage{todonotes}

\usepackage{marginnote}
\let\marginpar\marginnote

\begin{document}
Lorem ipsum
\todo{Bug}
\end{document}
```

**Comment by moi90** [comment]
Yes, I know that I can use `\let\marginpar\marginnote`.

But:

> I believe it should be possible without any hacks.

At the very least, the problem and its work-around should be mentioned in the documentation.

**Comment by FrankMittelbach** [comment]
@moi90 but the example given by Henrik shows that it is not a problem of todonotes but of standalone as that class fails if you use \marginpar, so it would be something that needs fixing there, or am I missing something?

**Comment by MartinScharrer** [comment]
Hi, yes, the `standalone` class does not support `\marginpar`. Usually the content is boxed and therefore there is no page margin which `\marginpar` can be used. Switching from the default 'crop' option to 'preview' (uses 'preview' package internally) changes the error message but still does not work. 

As `standalone` is actual intended for diagrams and similar content, not for running text, I personally don't minded this limitation so far. I am not sure on how to fix it. The margin handling of LaTeX would need to be copied somehow and that sounds not really easy for me.

**Comment by henrikmidtiby** [comment]
Thanks for your inputs to this case. 
I think it makes sense to include the workaround in the documentation for the todonotes package. It will be present in the next release.
