### ISSUE TITLE
Unwanted extra space is inserted if shadow option is used

### ISSUE THREAD

**Issue by rhstanton** [henrikmidtiby/todonotes#54]
If todonotes is loaded with the shadow option, an unwanted extra space is inserted with every \todo note. This does not happen if the shadow option is not used. Here's a simple example of a document displaying the problem:

```
\documentclass[12pt]{article}

% Uncomment just one of the following two lines
% \usepackage{todonotes}         % This works fine
\usepackage[shadow]{todonotes} % This adds an unwanted extra space

\begin{document}

This is a simple document\todo{Is there an extra space before the period?}.

\end{document}

```

**Comment by henrikmidtiby** [comment]
Thanks for the bug report. It has been fixed in version 1.1.5 which just have been uploaded to ctan.

bb722fb6cb473ec0c7b4996478d92aeb56946272
