### ISSUE TITLE
mycomment (1.8.4. from pdf) not working

### ISSUE THREAD

**Issue by danielp3011** [henrikmidtiby/todonotes#55]
Using the provided code in 1.8.4 from the todonotes package pdf does not display any todo, although it is not giving an error message.
The code used is the following: 
```
\newcounter{mycomment}
\newcommand{\mycomment}[2][]{%
% initials of the author (optional) + note in the margin
\refstepcounter{mycomment}%
{%
\setstretch{0.7}% spacing
\todo[color={red!100!green!33},size=\small]{%
\textbf{Comment [\uppercase{#1}\themycomment]:}~#2}%
}}

\mycomment[D]{test comment}

```
Any hints would be helpful. (Sorry if it is a stupid question I am just a startert with LaTex.)

**Comment by danielp3011** [comment]
Sry, seemed to be an error with overleaf. After relog in it worked

**Comment by henrikmidtiby** [comment]
Thanks for the update.
