### ISSUE TITLE
Incompatibility betwee IEEEcolor, xcolor, todonotes.

### ISSUE THREAD

**Issue by johnpenright** [henrikmidtiby/todonotes#58]
Recently an update to the `xcolor ` (November 2021) package seems to have broken something when using the `IEEEcolor ` class (this is a variant of the IEEETran clas) together with `todonotes`. 

The following steps will replicate this error:

1. Obtain the IEEE template (file attached from Sensors Journal)
[JSEN Latex.zip](https://github.com/henrikmidtiby/todonotes/files/7695347/JSEN.Latex.zip)
2. File should compile as-is without fatal errors (some figures are missing)
3. Adding \usepackage{todonotes} to the preamble will cause LaTeX compilation to fail

`> ! Package xcolor Error: Undefined color `subsectioncolor'.`

Other observations

- This seems to have been triggered by an xcolor.sty update last month.
- IEEEcolor and the new xcolor seem to work together. Only when todonotes is added is there a problem
- This doesn't seem to happen with the _article_ document-class.

**Comment by FrankMittelbach** [comment]
possibly related to: https://github.com/latex3/xcolor/issues/10

**Comment by FrankMittelbach** [comment]
fix is on route to ctan so the problem should be history in about 2-3 days

**Comment by henrikmidtiby** [comment]
I have tried to replicate the issue, but was not able to do that. Therefore I assume that the fix already is in place and hereby I close the issue.
