### ISSUE TITLE
High light text related to todos.

### ISSUE THREAD

**Issue by naught101** [henrikmidtiby/todonotes#6]
It'd be great to be able to be able to attach a todo not just to a point in text, but t a selection of text. This text should then be high lighted, or underlined, or bracketed, to show that it still needs work. If the text spans over multiple lines, perhaps a vertical line at the side could demarcate the text under consideration.

**Comment by henrikmidtiby** [comment]
The easy solution is to use the inline option for the inserted todos.

```
\documentclass{article}
\usepackage{todonotes}
\begin{document}
\todo[inline, caption={Text to appear in the list of todos}]{%
The long section of text that needs further work. 

This can span multiple lines and contain environments.
\begin{itemize}
\item	a
\item	b
\item	d
\end{itemize}
}
\end{document}
```
