### ISSUE TITLE
Conflict with package mathabx, \not cannot be used in todo note

### ISSUE THREAD

**Issue by martinfabian** [henrikmidtiby/todonotes#60]
Here is a minimum working example:
```
\documentclass{article}
\usepackage{mathabx} % Used for \bigtimes
\usepackage{todonotes}
\begin{document}
$\not\in$ % this works fine
\todo{$\not\in$} % this doesn't, unless \not is removed
\end{document}
```
When I compile this (on Overleaf) with pdfLaTeX, I get "undefined control sequence":
```
\not #1->\let \@@not 
                     =\not \let \@@n =\n \let \not =\relax \let \n =\relax \...
l.6 \todo{$\not\in$}
                     % Remove \not, and it works
```

**Comment by henrikmidtiby** [comment]
Thanks for the bug report and the minimal working example.
By removing things from the `todonotes.sty` file, I was able to reduce the example even further. 
It how has the form.

```
\documentclass{article}
\usepackage{mathabx}
\begin{document}
% this works fine
$\not\in$ 

% this doesn't, unless \not is removed
\addcontentsline{tdo}{todo}{$\not\in$}
\end{document}
```

When I compile the document on my local computer with pdflatex, I get the exact same error as you reported.

```
$ pdflatex test.tex 
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (TeX Live 2021) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-02-24> (/home/hemi/.TinyTeX/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(/home/hemi/.TinyTeX/texmf-dist/tex/latex/base/size10.clo)) (/home/hemi/.TinyTeX/texmf-dist/tex/generic/mathabx/mathabx.sty (/home/hemi/.TinyTeX/texmf-dist/tex/generic/mathabx/mathabx.dcl)) (/home/hemi/.TinyTeX/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def) (./test.aux)
! Undefined control sequence.
\not #1->\let \@@not 
                     =\not \let \@@n =\n \let \not =\relax \let \n =\relax \...
l.8 \addcontentsline{tdo}{todo}{$\not\in$}
                                          
? x
No pages of output.
Transcript written on test.log.
```

Based on the above, I expect that the issue origins from the `mathabx` package.

**Comment by FrankMittelbach** [comment]
They need to make that kind of definition robust in their package, that is all. It current does break anywhere where it is not immediately typeset. Try `\MakeRobust\not` in the preamble for now.

**Comment by martinfabian** [comment]
Yeah, `\MakeRobust\not` right after `\usepackage{mathabx}` fixes the issue for me. Great! Thanks.

**Comment by FrankMittelbach** [comment]
@martinfabian so would have `\protect`on an individual basis. But I think you should still tell it to the author of that package because these days one can expect such fragile definitions to be protected by default (in the past there was a good reason not to protect stuff due to space limitations but those days are long gone).
