### ISSUE TITLE
footmisc + marginfix + todonotes = error

### ISSUE THREAD

**Issue by AlMa0r** [henrikmidtiby/todonotes#71]
Feeding
```
\documentclass{article}
\usepackage{footmisc}
\usepackage{marginfix}
\usepackage{todonotes}
\begin{document}
\todo{test}
\end{document}
```
to `pdflatex` leads to a compilation error:
```
! Package marginfix Error: lost some margin notes.

See the marginfix package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.7 \end{document}
                  
?
```
Unfortunately, the explanation of “lost some margin notes” in § 13 of the documentation of marginfix says nothing to me. Having a bit more text, say,
```
\begin{document}
test

\todo{test}

test
\end{document}
```
doesn't help.

Used versions:

 - pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian)

 - LaTeX2e <2022-11-01>

 - L3 programming layer <2022-11-02>

 - article 2022/07/02 v1.4n

 - footmisc 2022/03/08 v6.0d

 - marginfix 2020/05/06 v1.2

 - todonotes 2021/06/04 v1.1.5

These versions were in TeX Live in Debian-testing this spring.

Who is the culprit?  Any more permanent bugfix than `\usepackage{footmisc}[=v5]` (thx to [David Carlisle](http://tex.stackexchange.com/a/652838))?

Crossposts: http://github.com/FrankMittelbach/fmitex-footmisc/issues/10 and http://github.com/shicks/marginfix/issues/19 .

Old version of the same bug: http://tex.stackexchange.com/questions/652835/footmisc-marginfix-todonotes-error .

Probably related: http://github.com/shicks/marginfix/issues/18 .

**Comment by FrankMittelbach** [comment]
nothing to do with todonotes - the same problem happens without loading the package and using a  `\marginpar` instead

**Comment by AlMa0r** [comment]
@FrankMittelbach Indeed. An even shorter non-working example is
```
\documentclass{article}
\usepackage{footmisc}
\usepackage{marginfix}
\begin{document}
\marginpar{test}
\end{document}

```
Therefore, closing the bug report with todonotes.
